# Generated by Django 4.1.2 on 2022-10-06 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FRBEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tns_name', models.CharField(blank=True, help_text='The name of the FRB from the Transient naming system.', max_length=64, null=True)),
                ('dm', models.FloatField(blank=True, null=True, verbose_name='Dispersion Measure (pc cm^-3)')),
                ('sn', models.FloatField(blank=True, null=True, verbose_name='Signal to noise ratio')),
                ('width', models.FloatField(blank=True, null=True)),
                ('search_path', models.FileField(max_length=1024, null=True, upload_to='candidates/')),
                ('image_path', models.FileField(max_length=1024, null=True, upload_to='candidates/')),
                ('histogram_path', models.FileField(max_length=1024, null=True, upload_to='candidates/')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('ra_hms', models.CharField(max_length=64)),
                ('dec_dms', models.CharField(max_length=64)),
                ('pos_error', models.FloatField()),
                ('source', models.CharField(choices=[('MB', 'Multibeam'), ('HT', 'High-time resolution pipleline')], max_length=3, verbose_name='The source that was used to calculate the candidate position.')),
                ('frb', models.ForeignKey(help_text='FRB event this position describes.', on_delete=django.db.models.deletion.CASCADE, to='cand_app.frbevent', verbose_name='FRB Event')),
            ],
        ),
    ]
