# Generated by Django 4.1.2 on 2022-10-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cand_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='pos_error',
        ),
        migrations.AddField(
            model_name='position',
            name='dec_pos_error',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='ra_pos_error',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
