# Generated by Django 4.1.2 on 2022-10-11 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cand_app', '0002_remove_position_pos_error_position_dec_pos_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
