# Generated by Django 4.1.2 on 2022-11-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cand_app', '0006_remove_frbevent_dm_remove_frbevent_sn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomeasurement',
            name='fluence',
            field=models.FloatField(blank=True, null=True, verbose_name='Fluence (Jy ms)'),
        ),
        migrations.AddField(
            model_name='radiomeasurement',
            name='fluence_err',
            field=models.FloatField(blank=True, null=True, verbose_name='Fluence Error (Jy ms)'),
        ),
    ]
