# Generated by Django 4.1.2 on 2022-11-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cand_app', '0007_radiomeasurement_fluence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomeasurement',
            name='flux',
            field=models.FloatField(blank=True, null=True, verbose_name='Flux Density (Jy)'),
        ),
        migrations.AddField(
            model_name='radiomeasurement',
            name='flux_err',
            field=models.FloatField(blank=True, null=True, verbose_name='Flux Density Error (Jy)'),
        ),
    ]
