# Generated by Django 4.1.2 on 2022-11-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cand_app', '0008_radiomeasurement_flux_radiomeasurement_flux_err'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomeasurement',
            name='gb',
            field=models.FloatField(default=1.0, verbose_name='Galactic Latitude (deg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiomeasurement',
            name='gl',
            field=models.FloatField(default=1.0, verbose_name='Galactic Longitude (deg)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radiomeasurement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VOEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xml_packet', models.CharField(max_length=10000)),
                ('radio_measurement', models.ForeignKey(help_text='The measurement that created this VOEvent', on_delete=django.db.models.deletion.CASCADE, to='cand_app.radiomeasurement', verbose_name='FRB Radio Measurement')),
            ],
        ),
    ]
