# Generated by Django 4.1.2 on 2022-11-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cand_app', '0009_radiomeasurement_gb_radiomeasurement_gl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voevent',
            name='comet_log',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
