# Generated by Django 4.1.2 on 2022-11-28 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cand_app', '0010_voevent_comet_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beam_semi_major_axis', models.FloatField(verbose_name='Beam Semi-major Axis (arcminutes)')),
                ('beam_semi_minor_axis', models.FloatField(verbose_name='Beam Semi-minor Axis (arcminutes)')),
                ('beam_rotation_angle', models.FloatField(verbose_name='Beam Rotation Angle (degrees)')),
                ('sampling_time', models.FloatField(verbose_name='Sampling Time (ms)')),
                ('bandwidth', models.FloatField(verbose_name='Bandwidth (MHz)')),
                ('nchan', models.IntegerField(verbose_name='nchan')),
                ('centre_frequency', models.FloatField(verbose_name='Centre Frequency (MHz)')),
                ('npol', models.IntegerField(verbose_name='npol')),
                ('bits_per_sample', models.IntegerField(verbose_name='Bits Per Sample')),
                ('gain', models.FloatField(verbose_name='Gain (K/Jy)')),
                ('tsys', models.FloatField(verbose_name='Tsys (K)')),
                ('backend', models.CharField(max_length=128, verbose_name='Backend')),
                ('beam', models.IntegerField(blank=True, help_text='Detection beam number if backend is a multi beam receiver', null=True, verbose_name='Beam Number')),
            ],
        ),
        migrations.AddField(
            model_name='frbevent',
            name='observation',
            field=models.ForeignKey(default=1, help_text='Observation that this FRB event was detected in.', on_delete=django.db.models.deletion.CASCADE, to='cand_app.observation', verbose_name='Observation'),
            preserve_default=False,
        ),
    ]
